export const LIST_ICONS = [
  { name: 'list-outline', label: 'General' },
  { name: 'briefcase-outline', label: 'Work' },
  { name: 'code-slash-outline', label: 'Coding' },
  { name: 'book-outline', label: 'Study' },
  { name: 'calculator-outline', label: 'Math' },
  { name: 'flask-outline', label: 'Science' },
  { name: 'leaf-outline', label: 'Biology' },
  { name: 'language-outline', label: 'Language' },
  { name: 'pencil-outline', label: 'Writing' },
  { name: 'document-text-outline', label: 'Assignment' },
  { name: 'school-outline', label: 'School' },
  { name: 'laptop-outline', label: 'Computer' },
  { name: 'clipboard-outline', label: 'Project' },
  { name: 'bulb-outline', label: 'Ideas' },
  { name: 'rocket-outline', label: 'Goals' },
  { name: 'heart-outline', label: 'Health' },
  { name: 'fitness-outline', label: 'Fitness' },
  { name: 'musical-notes-outline', label: 'Music' },
  { name: 'brush-outline', label: 'Art' },
  { name: 'camera-outline', label: 'Photography' },
  { name: 'game-controller-outline', label: 'Gaming' },
  { name: 'cart-outline', label: 'Shopping' },
  { name: 'restaurant-outline', label: 'Food' },
  { name: 'airplane-outline', label: 'Travel' },
  { name: 'home-outline', label: 'Home' },
];

